"""Test project to start using the Pillow library. Generates a github-like profile picture."""


import random
from typing import List

from PIL import Image


def generate_matrix(size: int = 10, amount_to_fill: int = 10) -> List[List[bool]]:
    """Generates a bi-dimensional boolean array simulating a
    profile picture like the ones generated by github.

    Args:
        size (int, optional): Size of the bi-dimensional array. Defaults to 10.
        amount_to_fill (int, optional): Amount of cells to fill in the array. Defaults to 10.

    Returns:
        List[List[bool]]: The bi-dimensional array containing filled and non-filled cells.
    """
    matrix = [[False] * size for _ in range(size)]
    while amount_to_fill > 0:
        row = random.randint(0, size - 1)
        col = random.randint(0, size - 1)
        if not matrix[row][col]:
            matrix[row][col] = matrix[row][size - col - 1] = True
            amount_to_fill -= 1
    return matrix


photo_matrix = generate_matrix()
pixels = []
for cur_row in photo_matrix:
    pixels = pixels + cur_row
conv_pixels = [1 if pixel else 0 for pixel in pixels]
img = Image.new('1', (len(photo_matrix), len(photo_matrix[0])))
img.putdata(conv_pixels)
resized = img.resize((1000, 1000), resample=Image.LANCZOS)
resized.save('black_white.png')
